train: /content/Fusar_Yolov7/train.txt  # 118287 images
val: /content/Fusar_Yolov7/val.txt  # 5000 images
nc: 15                                                      # Number of classes (change according to your dataset)
names: ["AggregatesCarrier","BulkCarrier","Cargo-HazardA","Cargo-HazardB","Cargo-HazardC","Cargo-HazardD","CargoShip","Cargo","DiveVessel","Dredger","Fishing","HighSpeedCraft","LawEnforce","Other","Passenger"]
























